### ISSUE TITLE
`Option search.lang 'pt-BR' is not supported, falling back to 'en'` error

### ISSUE THREAD

**Issue by gabrielbdornas** [infovote-io/dashboard#12]
Error during `mkdocs gh-deploy`.

**Comment by gabrielbdornas** [comment]
@danybonfil, please see in the [documentation](https://squidfunk.github.io/mkdocs-material/getting-started/) how we could fix this problem.

**Comment by danybonfil** [comment]
This bug was solved by including the "language: pt" under the theme configuration as shown below:



![Image](https://github.com/infovote-io/dashboard/assets/43021461/e10d58a1-40a6-4788-b557-3a749471b7b3)
