### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by gabrielbdornas** [infovote-io/dashboard#14]
@danybonfil, please configure the domain as suggested [here](https://code.braico.me/blog/2022-07-04-github-pages-custom-domain-configuration.html).

**Comment by danybonfil** [comment]
Verified Status

<img width="158" alt="image" src="https://github.com/infovote-io/dashboard/assets/43021461/5b228123-3f24-4a86-be50-936f591ea032">

**Comment by gabrielbdornas** [comment]
@danybonfil, problem solved.

This warning is showing, but it's probably due DNS propagation.

![image](https://github.com/infovote-io/dashboard/assets/49699290/7b8bdeb7-447f-47cb-876d-c3d1b4c1bd5f)

Let's close this issue and if the warning persists we could open a specific for this (with low priority due to no problem with the published document).

**Comment by danybonfil** [comment]
Before the solution provided by @gabrielbdornas I followed this [tutorial](https://github.com/orgs/community/discussions/35168) to remove the verified domain and try again. It did not work

**Comment by danybonfil** [comment]
The Github virtual assistant gave this response "Domain does not resolve to the GitHub Pages server" and then suggested troubleshooting for SSL errors instead



![Image](https://github.com/infovote-io/dashboard/assets/43021461/c36f6492-79a4-4fd3-95a0-470f1856b952)
