### ISSUE TITLE
domain improper configuration

### ISSUE THREAD

**Issue by danybonfil** [infovote-io/dashboard#21]
after a `$git push` to include new pages like "dashboard.md" and its update into "mkdocs.yml" 
the domain appears to break and you must go into github > pages to add it again

<img width="896" alt="image" src="https://github.com/infovote-io/dashboard/assets/43021461/c81d7379-eb30-4887-8830-2e812456bd34">

**Comment by gabrielbdornas** [comment]
Fixed
